### ISSUE TITLE
RTE when using PIXI v5

### ISSUE THREAD

**Issue by Patrick-Hammond** [pixijs/pixi-sound#80] opened 2019-01-04 12:46 UTC
The example pages are getting the latest pixi dev:
` <script src="https://pixijs.download/dev/pixi.min.js"></script>`

Which happens to be v5 now I guess.

It's complaining about the loader override..

LoaderMiddleware.ts:32 Uncaught TypeError: Cannot set property Loader of #<Object> which has only a getter
    at Function.e.install (LoaderMiddleware.ts:32)
    at Function.e.init (SoundLibrary.ts:139)
    at index.ts:13
    at pixi-sound.js:9
    at pixi-sound.js:9

Changing to the last v4 version of PIXI seems to fix it e.g. change script tags to:
`<script src="https://pixijs.download/v4.8.4/pixi.min.js"></script>`

**Comment by bigtimebuddy** [comment] 2019-01-07 23:44
Fixed with #82, LoaderMiddleware now works with v5 Loader plugins

**Comment by koko236** [comment] 2019-04-24 15:43
I'm trying to use pixi-sound v2.1.3 with pixi.js v5.0 as in package.json below:
```
"pixi-sound": "^2.1.3",
"pixi.js": "^5.0.0-rc.3",
```
Then I tried to import both libraries in many ways: 
```
import 'pixi.js';
import 'pixi-sound';
```
as suggested [here](https://github.com/pixijs/pixi-sound/issues/50#issuecomment-350337149).
But it throws this runtime error:
```
Uncaught PixiJS required
```
If I manage to convince the `pixi-sound` that pixi exists, eg. going a really ugly path:
```
import * as PIXI from 'pixi.js';

window.PIXI = PIXI;
PIXI.loaders = PIXI; /// HACK trying to solve missing loaders

console.log("Ssdsds");
let Sound = require('pixi-sound');
```
It starts to complain about another missing property:
```
Uncaught TypeError: Cannot read property 'setExtensionXhrType' of undefined
```
The takeaway being that either I'm doing something terribly wrong or both libraries seem to be still incompatibile despite the commit comments.

**Comment by meiraxx** [comment] 2019-05-08 17:48
Same issue

**Comment by Zambiorix** [comment] 2019-05-09 13:55
I have the same issues with :
```
"pixi-sound": "^2.1.4",
"pixi.js-legacy": "^5.0.2"
```

I have tried many ways (also the suggestions above) to get it working, but I can't get it to work...

Is there a hack I can use until this gets solved?

Thanks

**Comment by bigtimebuddy** [comment] 2019-05-09 14:16
I’m working on a v5 release. Coming soon.

**Comment by bigtimebuddy** [comment] 2019-05-09 14:35
One thing worth trying, as a workaround, would be this:

```js
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
PIXI.useDeprecated();
import sound from 'pixi-sound';
```

The `useDeprecated` call is the important part, because if you are building using Webpack or some other bundler, deprecations aren't applied because no global is added. In this case the error is because PIXI.loaders.Resource is now PIXI.LoaderResource in v5.

**Comment by Zambiorix** [comment] 2019-05-09 14:39
Didn't work for me.
When do you think v5 release is coming? Matter of hours, days, weeks?
Just to have an idea :-)

**Comment by bigtimebuddy** [comment] 2019-05-09 14:48
Probably a day or two. It's mostly done, just need to validate it bundles. Are you using Webpack @Zambiorix?

**Comment by bigtimebuddy** [comment] 2019-05-09 14:49
Alternatively, this might work too:

```js
import "pixi.js/dist/pixi.min.js";
import "pixi-sound";
```

**Comment by Zambiorix** [comment] 2019-05-09 15:07
I'm using webpack
No that didn't work

I'm working with Pixijs v5 Legacy and the only way I can get my app working is when I import like this
```
import * as PIXI from "pixi.js-legacy"
```

When I change to 
```
import "pixi.js/dist/pixi.min.js";
or
import "pixi.js-legacy/dist/pixi-legacy.min.js";
```
My sprites are not loading but I don't get a RTE

As soon as I import
```
import "pixi-sound";
```

I get a RTE 
```
Uncaught PixiJS required
```

**Comment by bigtimebuddy** [comment] 2019-05-09 15:21
I think I understand what’s happening. Give me a today to try to get a release out.

**Comment by Zambiorix** [comment] 2019-05-09 15:28
Thanks! You don't have to rush for me... My app doesn't include sound yet, I was just testing the integration. Won't work on audio until next week or so

**Comment by bigtimebuddy** [comment] 2019-05-09 16:01
You're not the only person that's been asking for a functional version of sound since PixiJS v5 came out.

**Comment by bigtimebuddy** [comment] 2019-05-09 20:19
Released version v3.0.0 which resolves all these bundling issues.

Here's a working example using Webpack:
https://github.com/bigtimebuddy/pixi-sound-webpack-example

**Closed by bigtimebuddy** 2019-05-09 20:19 UTC
Labels: bug

**Comment by cmfcmf** [comment] 2019-05-09 21:14
I am wondering if there was a specific reason to move the pixi.js dependency/ies from `peerDependencies` into just `dependencies`? Or was that and oversight maybe? https://github.com/pixijs/pixi-sound/blob/265e84b41ed4c09b3adee076cd9cefdd84024996/package.json#L79-L84

**Comment by bigtimebuddy** [comment] 2019-05-09 21:19
@cmfcmf the paradigm in PixiJS v5 has changed a little with regard to bundlers. In PixiJS v4, all of the APIs were shared using a global `PIXI` object. In this case a peer dependency was appropriate. We have removed that global object in v5 for bundlers because creating a single object with everything invalidates tree-shaking. Also, exposing PIXI globally is not great if you want to prevent people from mucking with your app/game.

Having real dependencies reflects the APIs within PixiJS v5 that are actually being utilized. It's much better for tree-shaking in Webpack or Rollup.

**Comment by rocket-ua** [comment] 2019-09-02 19:00
Hi. I have problem with pixi-sound and webpack.
I import pixi-sound like this:
`import Sound from 'pixi-sound';
`
And than use sound:
`Sound.play('BallSound');
`
But i have error:

> Uncaught TypeError: Cannot read property 'play' of undefined
>     at t.play (pixi-sound.esm.js:9)

"pixi-sound": "^3.0.3",
"pixi.js": "^5.1.2",
"webpack": "^4.32.2"

**Comment by bigtimebuddy** [comment] 2019-09-02 20:19
@rocket-us please file a new issue, preferably on pixi-sound. Also, please include a repo that reproduces your issue, as that could be caused by a bunch of things and it’s difficult to diagnose with so little information.

**Comment by rocket-ua** [comment] 2019-09-03 08:57
> @rocket-ua please file a new issue. Also, please include a repo that reproduces your issue, as that could be caused by a bunch of things and it’s difficult to diagnose with so little information.

hmmm. Now i think i have another problem. pixi-sound can't find my sound by alias. I load my sound using pixi loader
