### ISSUE TITLE
[bug]: throw exception when load video(set loadType = 4)

### ISSUE THREAD

**Issue by koalaylj** [pixijs/pixi-sound#75] opened 2018-09-30 08:31 UTC
```javascript
var loader = new PIXI.loaders.Loader()
loader.add('assets/video.mp4',{loadType:4}).load()
```
this will cause pixi-sound throw exception. if we dont set {loadType:4},no exception occurs but loaders's resource list can not read video data(it's empty).

I found code that in SoundUtils.ts file at`line 72`,
```javascript
const types:{[key:string]:string} = {m4a:"mp4",oga:"ogg"}
```
if I delete`m4a:"mp4"` ,it will work all right without any exception .
why load mp4 as a sound file?

**Comment by bigtimebuddy** [comment] 2019-04-23 01:52
Duplicate of #69

**Closed by bigtimebuddy** 2019-04-23 01:52 UTC
